micronaut:
  application:
    name: JWTTestKit
  server:
    port: ${APPLICATION_PORT:8080}
  security:
    enabled: true
    token:
      jwt:
        signatures:
          jwks:
            JWTTestKit:
              url: http://localhost:8080/JWTTestKit/jwks
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

endpoints:
  all:
    port: ${MANAGEMENT_PORT:8082}
  health:
    enabled: true
    sensitive: false
    details-visible: NEVER