micronaut:
  application:
    name: JWTTestKit

  server:
    port: ${APPLICATION_PORT:8080}

  router:
    static-resources:
      swagger:
        paths: classpath:swagger
        mapping: /swagger/**
      swagger-ui-res:
        paths: classpath:META-INF/swagger/views/swagger-ui/res
        mapping: /swagger-ui/res/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /api/**

  openapi:
    target:
      file: "src/main/resources/swagger/api.yaml"

  security:
    enabled: true
    intercept-url-map:
      - pattern: /api/**
        access:
          - isAnonymous()
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()

    token:
      jwt:
        signatures:
          jwks:
            JWTTestKit:
              url: http://localhost:8080/JWTTestKit/jwks

endpoints:
  all:
    port: ${MANAGEMENT_PORT:8082}
  health:
    enabled: true
    sensitive: false
    details-visible: NEVER

netty:
  default:
    allocator:
      max-order: 3


#api:
#  version: 1.0.0
#
#openapi:
#  target:
#    file: "src/main/resources/swagger"
#  info:
#    title: JWT Test Kit API
#    version: ${api.version}
#    description: API for generating and managing JWT tokens for testing purposes
#  tags:
#    - name: JWT Test Kit
#      description: APIs for JWT token generation and key management