name: JWTTestKit Pull Request Validation
on: [pull_request]

permissions:
  packages: write

jobs:
  build:
    name: Standard build and test
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b
        with:
          validate-wrappers: true

      - name: Run Tests
        run: ./gradlew test -i --no-daemon

      - name: Test Build Image
        run: ./gradlew dockerBuild -i --no-daemon

  build-native:
    name: Native build and test
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: graalvm/setup-graalvm@aafbedb8d382ed0ca6167d3a051415f20c859274
        with:
          java-version: '21'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b
        with:
          validate-wrappers: true

      - name: Run Tests
        run: ./gradlew nativeTest -i --no-daemon

      - name: Test Build Native Image
        run: ./gradlew optimizedDockerBuildNative -i --no-daemon

  cleanup:
    name: ghcr.io cleanup action
    needs: [build, build-native]
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: jwttestkit
          delete-tags: "*-snapshot,*-snapshot-*"
          exclude-tags: "1.1-snapshot"
          delete-untagged: true
          dry-run: true